apiVersion: v1
kind: Secret
metadata:
  name: kg-platform-secret
  namespace: kg-platform
type: Opaque
stringData:
  MYSQL_PASSWORD: change_me
  KG_JWT_SECRET: change_me_to_a_random_32_plus_length_secret
