apiVersion: v1
kind: Service
metadata:
  name: kg-system
  namespace: kg-platform
spec:
  selector:
    app: kg-system
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
